function love.conf(t)
    t.title = "jDurak"          -- The title of the window the game is in (string)
    t.author = "alexd2580"      -- The author of the game (string)
    t.url = "http://github.com/alexd2580/jDurak"  -- The website of the game (string)
    t.version = "0.10.0"        -- The LÖVE version this game was made for (string)
    t.console = false           -- Attach a console (boolean, Windows only)
    t.release = false           -- Enable release mode (boolean)
    t.window.width = 800        -- The window width (number)
    t.window.height = 600       -- The window height (number)
    t.window.fullwindow = false -- Enable fullwindow (boolean)
    t.window.vsync = true       -- Enable vertical sync (boolean)
    t.window.fsaa = 0           -- The number of FSAA-buffers (number)
    t.modules.joystick = false  -- Enable the joystick module (boolean)
    t.modules.audio = false     -- Enable the audio module (boolean)
    t.modules.keyboard = true   -- Enable the keyboard module (boolean)
    t.modules.event = true      -- Enable the event module (boolean)
    t.modules.image = true      -- Enable the image module (boolean)
    t.modules.graphics = true   -- Enable the graphics module (boolean)
    t.modules.timer = true      -- Enable the timer module (boolean)
    t.modules.mouse = true      -- Enable the mouse module (boolean)
    t.modules.sound = false     -- Enable the sound module (boolean)
    t.modules.physics = false   -- Enable the physics module (boolean)
end

--134.28.70.143
